name: 'Deploy to AWS S3'
description: 'Deploy static website to AWS S3'
inputs:
  bucket:
    description: 'The name of the S3 bucket to deploy to'
    required: true
  bucket-region:
    description: 'The AWS region where the bucket is located'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the files to deploy'
    required: true
outputs:
  websiteurl:
    description: 'The URL of the deployed website'
runs:
  using: 'docker'
  image: 'Dockerfile'